import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const moduleDirectory = dirname(fileURLToPath(import.meta.url));

/** Repository root, resolved from this file's location rather than cwd. */
export const ProjectRoot = resolve(moduleDirectory, '..', '..');

export const DataDirectory = join(ProjectRoot, 'Data');
export const CuratedDirectory = join(DataDirectory, 'Curated');
export const SnapshotDirectory = join(DataDirectory, 'Snapshot');

/** Committed to git so a reviewer can clone and run without a full ingest. */
export const SnapshotDatabasePath = join(SnapshotDirectory, 'Airports.db');

/** L1 raw-response cache. Gitignored; regenerated by `npm run ingest`. */
export const HttpCacheDirectory = join(ProjectRoot, '.cache', 'http');

export const CuratedFacilitiesPath = join(CuratedDirectory, 'AirportFacilities.json');
export const RegionsPath = join(CuratedDirectory, 'Regions.json');
